name: soul_meet_num
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.1
  dropdown_search: ^5.0.6
  image_picker: ^1.0.4
  firebase_auth: ^4.10.1
  modal_progress_hud_nsn: ^0.4.0
  firebase_core: ^2.17.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
  like_button: ^2.0.5
  supabase_flutter: ^1.10.18
  timeago: ^3.1.0
  flutter_dotenv: ^5.1.0
  powersync: ^0.4.0
  logging: ^1.2.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.1.0
  swipe_cards: ^2.0.0+1
  flutter_range_slider_ns: ^0.0.2
  http_auth: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/foreground_icon.png"

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
    - lib/Services/localization/json_languages/
